l_english:
 pm_no_equipment: "$pm_no_steam_automation$"

 pm_picks_and_shovels_building_coal_mine: "Improved Coal Mining Tools"
 pm_picks_and_shovels_building_iron_mine: "Improved Iron Mining Tools"
 pm_picks_and_shovels_building_lead_mine: "Improved Lead Mining Tools"
 pm_picks_and_shovels_building_sulfur_mine: "Improved Sulfur Mining Tools"
 pm_picks_and_shovels_building_gold_mine: "Improved Gold Mining Tools"
 
 #pm_simple_farming: "Simple Farming"
 #pm_simple_farming_building_rice_farm: "Simple Farming"

 #pm_basic_shipbuilding: "Improved Wood Ships"
