name: Main

on: push

jobs:
  yamllint:
    name: Lint localization/ with yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install requirements
        run: pip install --requirement scripts/lint/requirements.txt
      - name: Lint
        run: python scripts/lint/yaml.py --directory localization/
             --paths-to-ignore
             "localization/korean/ib_l_korean .yml"
             "localization/english/br_events_l_english.yml"
